INSERT INTO dispatch_statuses (name) VALUES
    ('pending'),
    ('in_transit'),
    ('delivered'),
    ('not_delivered'),
    ('returned'),
    ('address_review'),
    ('in_planning'),
    ('scheduled'),
    ('assigned'),
    ('out_for_delivery'),
    ('incident'),
    ('rescheduled'),
    ('pickup_scheduled'),
    ('picked_up_in_transit'),
    ('returned_to_warehouse');
